language: node_js

node_js:
  - '0.12'
  - '0.11'
  - '0.10'

services: mongodb

before_install: npm install forever -g

before_script: forever start ./server/bin/www

after_script: forever stop ./server/bin/www

# after_success: npm run coveralls

deploy:
  provider: heroku
  api_key:
    secure: GtdKMYvxE9XE4nbcANpS2juBPZE6nRQw4qS84L8rUpkgFoTJXTH7HEMrdEi9Te5KcJIempCKbTRa/GXkKVP0OLy7S0Aox66eiwd4qlVQzPkZpqp2LI7ltftDg+SoKni4+DX+7euZanc3v7exhbEMs/RRT3eAZ5dUItF2FC1sCW8=
  app: pacific-beach-3008
  on:
    branch: master
    node: '0.12'